local ComponentsProps = {

    Toys = {

        {
            hashid = "toys_1",
            always_attached = false,
            category = "toys",
            model = 'p_bathbrush01x',
            bone = 'skel_neck2',
            offset = {
                x = 0.0,
                y = -0.20,
                z = 0.08,
                pitch = -30.0,
                roll = 15.0,
                yaw = 180.0,
            },
        },
        {
            hashid = "toys_2",
            always_attached = false,
            category = "toys",
            model = 's_inv_voodoodoll01x',
            bone = 'skel_neck0',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_6",
            always_attached = false,
            category = "toys",
            model = 'p_voodoodoll01x',
            bone = 'skel_neck0',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_3",
            always_attached = false,
            category = "toys",
            model = 'p_stethascope01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_4",
            always_attached = false,
            category = "toys",
            model = 's_squirrelmarston01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_5",
            always_attached = false,
            category = "toys",
            model = 'p_tuxyoungaligator01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_7",
            always_attached = false,
            category = "toys",
            model = 's_re_relicguama01x',
            bone = 'skel_neck0',
            offset = {
                x = 0.0,
                y = 0.0,
                z = 0.14,
                pitch = 0.0,
                roll = 0.0,
                yaw = 270.0,
            },
        },
        {
            hashid = "toys_8",
            always_attached = false,
            category = "toys",
            model = 's_re_silver_relicguama01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_9",
            always_attached = false,
            category = "toys",
            model = 'p_blowgundart01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_10",
            always_attached = false,
            category = "toys",
            model = 'p_snoeshoe01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_11",
            always_attached = false,
            category = "toys",
            model = 'p_doll02x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "toys_12",
            always_attached = false,
            category = "toys",
            model = 'p_doll01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
    },
    Horns = {
        {
            hashid = "horns_1",
            always_attached = false,
            category = "horns",
            model = 's_mountedmooseantlers01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "horns_2",
            always_attached = false,
            category = "horns",
            model = 'p_antlers01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "horns_3",
            always_attached = false,
            category = "horns",
            model = 'p_scoutfireelkantlers01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "horns_4",
            always_attached = false,
            category = "horns",
            model = 'p_antlers04x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "horns_5",
            always_attached = false,
            category = "horns",
            model = 'p_pronghornskull01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "horns_6",
            always_attached = false,
            category = "horns",
            model = 'p_horn01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

    },
    Neck = {

        {
            hashid = "neck_1",
            always_attached = false,
            category = "neck",
            model = 'p_disdreamcatcherwind01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_2",
            always_attached = false,
            category = "neck",
            model = 'p_disdreamcatcherwind05x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_3",
            always_attached = false,
            category = "neck",
            model = 's_quasifuturisticrock01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_4",
            always_attached = false,
            category = "neck",
            model = 'p_flask02x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_5",
            always_attached = false,
            category = "neck",
            model = 's_re_relicguama02x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_6",
            always_attached = false,
            category = "neck",
            model = 's_re_goldrelicguama01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_7",
            always_attached = false,
            category = "neck",
            model = 'p_ancientfertilityfgr01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_8",
            always_attached = false,
            category = "neck",
            model = 's_urndiscoverable01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_9",
            always_attached = false,
            category = "neck",
            model = 'p_jug01bx',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_10",
            always_attached = false,
            category = "neck",
            model = 'p_cs_noose01xb',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_11",
            always_attached = false,
            category = "neck",
            model = 'p_cs_rope05x_coiled',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "neck_12",
            always_attached = false,
            category = "neck",
            model = 's_ropecanoeend02x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
    },
    Medal = {

        {
            hashid = "medal_1",
            always_attached = false,
            category = "medal",
            model = 'p_eaglependant01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "medal_2",
            always_attached = false,
            category = "medal",
            model = 'p_deputybadge01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "medal_3",
            always_attached = false,
            category = "medal",
            model = 's_pantherclawtrinket01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "medal_4",
            always_attached = false,
            category = "medal",
            model = 's_coachlock02x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "medal_5",
            always_attached = false,
            category = "medal",
            model = 's_wagonprison_lock',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "medal_6",
            always_attached = false,
            category = "medal",
            model = 's_wagonprison_lock',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "medal_7",
            always_attached = false,
            category = "medal",
            model = 'p_ancientmayanhead01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "medal_8",
            always_attached = false,
            category = "medal",
            model = 'p_cs_warmedal01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
    },
    Masks = {
        {
            hashid = "mask_1",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull06x',
            bone = 'PH_HeadProp',
            offset = {
                x = 0.08,
                y = -0.04,
                z = 0.0,
                pitch = 45.0,
                roll = 270.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_2",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_3",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull02x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_4",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull03x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_5",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull04x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_6",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull05x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.11,
                y = 0.0,
                z = 0.00,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_8",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull07x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_9",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull08x',
            bone = 'PH_HeadProp',
            offset = {
                x = 0.08,
                y = -0.04,
                z = 0.0,
                pitch = 45.0,
                roll = 270.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_10",
            always_attached = false,
            category = "mask",
            model = 'mp005_p_mp_predhunt_skull09x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_11",
            always_attached = false,
            category = "mask",
            model = 'p_mask01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_12",
            always_attached = false,
            category = "mask",
            model = 'p_mask02x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_13",
            always_attached = false,
            category = "mask",
            model = 'p_mask03x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_14",
            always_attached = false,
            category = "mask",
            model = 'p_mask04x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_15",
            always_attached = false,
            category = "mask",
            model = 'p_mask05x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_16",
            always_attached = false,
            category = "mask",
            model = 'p_maskolmec01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_17",
            always_attached = false,
            category = "mask",
            model = 's_ramskull01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
        {
            hashid = "mask_18",
            always_attached = false,
            category = "mask",
            model = 'p_skullmoose01x',
            bone = 'PH_HeadProp',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

    },
    Cigar = {

        {
            hashid = "cigar_1",
            always_attached = false,
            category = "cigar",
            model =  'p_cigar01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "cigar_2",
            always_attached = false,
            category = "cigar",
            model =  'p_cigar02x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "cigar_3",
            always_attached = false,
            category = "cigar",
            model =  'p_cigarette_cs01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "cigar_4",
            always_attached = false,
            category = "cigar",
            model =  'p_cigaretteholder01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "cigar_5",
            always_attached = false,
            category = "cigar",
            model =  'p_pipe01x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "cigar_6",
            always_attached = false,
            category = "cigar",
            model =  'p_pipe02x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "cigar_7",
            always_attached = false,
            category = "cigar",
            model =  'p_pipe03x',
            bone = 'PH_Head',
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },

        {
            hashid = "cigar_8",
            always_attached = false,
            category = "cigar", -- category
            model =  'p_opiumpipe01x', -- model
            bone = 'PH_Head', -- bone
            offset = {
                x = -0.05,
                y = 0.0,
                z = 0.0,
                pitch = 0.0,
                roll = 0.0,
                yaw = 0.0,
            },
        },
    },
}

return ComponentsProps